### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Officialkarz** [RadonCoding/rusty-clipper#1]
Startup not working

**Comment by RadonCoding** [comment]
I'm going to look into this and let you know if i can reproduce the issue.

**Comment by RadonCoding** [comment]
Hello. I'm unable to reproduce this issue could you provide some more information?

**Comment by Officialkarz** [comment]
Also is it possible to add more Tokens by adding  the regex of other tokens eg DASH DOGE TRX XRP
Or is the code limited to to just BTC ETH AND LTC along???

**Comment by Officialkarz** [comment]
> Hello. I'm unable to reproduce this issue could you provide some more information?

Okay I will don that and get back to you asap in the mean time i drop a question for you above for you

**Comment by RadonCoding** [comment]
> Also is it possible to add more Tokens by adding the regex of other tokens eg DASH DOGE TRX XRP Or is the code limited to to just BTC ETH AND LTC along???

you're free to add support for any crypto currencies just check what i've done with bitcoin for example

**Comment by Officialkarz** [comment]
Hello i was able to add more crypto currencies but not it takes time to paste after its been copied and i  dont know where i can adjust the line setting on the script.i don mind if you can tell me . Also how can i change the directory where the file  copies too apart from the temp folder? Thanks
